# Generated by Django 4.1.2 on 2022-11-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(help_text='Logradouro', max_length=120)),
                ('numero', models.CharField(help_text='Número', max_length=10, null=True)),
                ('complemento', models.CharField(help_text='Complemento', max_length=50, null=True)),
                ('bairro', models.CharField(help_text='Bairro', max_length=80)),
                ('estado', models.CharField(help_text='Estado', max_length=20)),
                ('cep', models.CharField(help_text='CEP', max_length=9)),
            ],
            options={
                'db_table': 'Endereco',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomeProduto', models.CharField(help_text='Nome do produto', max_length=50)),
                ('preco', models.FloatField()),
                ('imagem', models.CharField(help_text='Imagem do produto', max_length=180)),
            ],
            options={
                'db_table': 'Produto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomeUsuario', models.CharField(help_text='Nome completo', max_length=60)),
                ('cpfOuCnpj', models.CharField(help_text='CPF - Ex: 1234567891011', max_length=13, unique=True)),
                ('celular', models.CharField(help_text='Número para contato', max_length=12)),
                ('email', models.EmailField(help_text='Email', max_length=20, unique=True)),
                ('senha', models.CharField(help_text='Senha', max_length=20)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOmmerce.endereco')),
            ],
            options={
                'db_table': 'Usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ECOmmerce.usuario')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ECOmmerce.produto')),
            ],
            options={
                'db_table': 'Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomeCategoria', models.CharField(help_text='Nome da categoria', max_length=50)),
                ('produtos', models.ManyToManyField(to='ECOmmerce.produto')),
            ],
            options={
                'db_table': 'Categoria',
                'ordering': ['nomeCategoria'],
            },
        ),
    ]
