# Generated by Django 4.1.1 on 2022-10-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(help_text='Logradouro', max_length=120)),
                ('numero', models.CharField(help_text='Número', max_length=10, null=True)),
                ('complemento', models.CharField(help_text='Complemento', max_length=50, null=True)),
                ('bairro', models.CharField(help_text='Bairro', max_length=80)),
                ('estado', models.CharField(help_text='Estado', max_length=20)),
                ('cep', models.CharField(help_text='CEP', max_length=9)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomeProduto', models.CharField(help_text='Nome do produto', max_length=50)),
                ('preco', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomeUsuario', models.CharField(help_text='Nome completo', max_length=60)),
                ('cpf', models.CharField(help_text='CPF - Ex: 1234567891011', max_length=11, unique=True)),
                ('cnpj', models.CharField(help_text='CPF - Ex: 1234567891011', max_length=11, unique=True)),
                ('celular', models.CharField(help_text='Número para contato', max_length=12)),
                ('email', models.EmailField(help_text='Email', max_length=20, unique=True)),
                ('tipoUsuario', models.CharField(choices=[('PJ', 'Pessoa Juridica'), ('PF', 'Pessoa Fisica')], max_length=2)),
                ('senha', models.CharField(help_text='Senha', max_length=20)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOmmerce.endereco')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomeCategoria', models.CharField(help_text='Nome da categoria', max_length=50)),
                ('produtos', models.ManyToManyField(to='ECOmmerce.produto')),
            ],
            options={
                'ordering': ['nomeCategoria'],
            },
        ),
    ]
