# Generated by Django 4.1.2 on 2022-11-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOmmerce', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('insert into "Produto" values (1, \'Pêra Maçã Anã\', \'Na Índia, chama-se nashipati e em Bangladesh e no Nepal conhecida como nash-paty.\', \'Pyrus pyrifolia\', 120.00, \'https://cdn.awsli.com.br/600x450/163/163535/produto/124316733/0eb4a98c1e.jpg\');'),
        migrations.RunSQL('insert into "Produto" values (2, \'Pimenta do Reino\', \'Nativa da Índia, é também conhecida como pimenta-negra e é considerada um dos cinco artigos mais luxuosos.\', \'Piper nigrum\', 20.00, \'https://cdn.awsli.com.br/600x450/163/163535/produto/5830540/334c144076.jpg\');'),
        migrations.RunSQL('insert into "Produto" values (3, \'Mini Romã Bonsai\', \'Nativa do Oriente Médio, a romã recebeu ao longo do tempo significados de prosperidade.\', \'Punica granatum\', 180.00, \'https://cdn.awsli.com.br/1000x1000/163/163535/produto/6341671/a924d444cc.jpg\');'),
        migrations.RunSQL('insert into "Produto" values (4, \'Pitanga Bonsai 2 anos\', \'Nativas da Mata Atlântica brasileira, as pitangueiras são rústicas e produzem saborosos frutos.\', \'ybápytanga\', 90.00, \'https://cdn.awsli.com.br/1000x1000/163/163535/produto/9202799/b85e11c341.jpg\');')
    ]
