# Generated by Django 4.1.2 on 2022-11-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECOmmerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ECOmmerce.usuario')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ECOmmerce.produto')),
            ],
        ),
    ]
